app:
  flask_env: "production"
  flask_app: "backend/wsgi.py"
  rebuild_app: true
  debug: false
database:
  type: "postgresql"
  host: "localhost"
  port: 5432
  user: "postgres"
  password: ${DB_PASSWORD}
  db_name: "finiautoma_prod"
  schema: "data"
default:
  user_id: 0
  user_name: "Default"
deploy:
  SERVER_NAME: ec2-56-228-12-164.eu-north-1.compute.amazonaws.com
  USER: ubuntu
  REMOTE_PATH: ~/app
  LOCAL_PATH: .
  PEM_FILE: ../aws/slovakia-viki-asus.pem