app:
  flask_env: "development"
  flask_app: "app"
  rebuild_app: true
  debug: true
database:
  type: "postgresql"
  host: "localhost"
  port: 5432
  user: "fini_user"
  password: ${DB_PASSWORD}
  db_name: "postgres"
